# Generated by Django 4.1.7 on 2023-04-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiesOpskrifter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('oprindelse', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('kitchen', models.CharField(max_length=200)),
                ('Link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Opskrifter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('URL', models.CharField(max_length=200)),
                ('Oprettet_dato', models.DateField(verbose_name='Dato oprettet')),
            ],
        ),
    ]
