# Generated by Django 4.1.7 on 2023-05-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_miesopskrifter_comment_miesopskrifter_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miesopskrifter',
            old_name='Link',
            new_name='link',
        ),
    ]
