# Generated by Django 4.1.7 on 2023-05-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_link_miesopskrifter_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='miesopskrifter',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
